import { Link } from 'react-router-dom';
import './Legal.css';

const sections = [
    {
        id: 'collect',
        tag: 'Data Collection',
        title: 'Information We Collect',
        content: (
            <>
                <p>We collect only the information necessary to provide the tutoring platform. This includes:</p>
                <ul>
                    <li><strong>Account information:</strong> your first name, last initial, email address, grade level, and school year.</li>
                    <li><strong>Tutor application data:</strong> subjects you wish to teach, teacher reference name, and quiz results.</li>
                    <li><strong>Session records:</strong> date, subject, duration, and confirmation status for each tutoring session.</li>
                    <li><strong>Platform activity:</strong> course progress, quiz completions, and flashcard usage stored locally in your browser.</li>
                </ul>
                <div className="legal-highlight">We do not collect your full name publicly. Only your first name and last initial appear on your profile, visible to other platform users.</div>
            </>
        )
    },
    {
        id: 'use',
        tag: 'How We Use It',
        title: 'How We Use Your Information',
        content: (
            <>
                <p>The information we collect is used solely to operate and improve the platform:</p>
                <ul>
                    <li>Matching students with qualified tutors based on subject and availability.</li>
                    <li>Tracking and verifying tutor service hours for certificate generation.</li>
                    <li>Sending session confirmation and status notifications.</li>
                    <li>Reviewing tutor applications and enforcing community guidelines.</li>
                    <li>Generating anonymized usage statistics to improve content and features.</li>
                </ul>
                <p>We do not use your information for advertising, profiling, or any commercial purpose.</p>
            </>
        )
    },
    {
        id: 'sharing',
        tag: 'Third Parties',
        title: 'Data Sharing',
        content: (
            <>
                <p>We do not sell, rent, or share your personal information with third parties for commercial purposes. Your data may be accessed by:</p>
                <ul>
                    <li><strong>Platform administrators:</strong> the Equalizer student leadership team and our faculty advisor, for application review and dispute resolution.</li>
                    <li><strong>Your school:</strong> only when you choose to submit a service hour certificate generated by the Platform. The certificate contains only session totals, not personal communications.</li>
                </ul>
                <p>We do not integrate with advertising networks, analytics vendors, or data brokers.</p>
            </>
        )
    },
    {
        id: 'ferpa',
        tag: 'Student Rights',
        title: 'Student Data and FERPA',
        content: (
            <>
                <p>As a school-affiliated platform serving students, we are committed to complying with the Family Educational Rights and Privacy Act (FERPA) and applicable state student privacy laws.</p>
                <ul>
                    <li>Student education records are not disclosed to unauthorized parties.</li>
                    <li>Parents or guardians of minor students may request access to or deletion of their child's data by contacting us through the <Link to="/contact">Contact page</Link>.</li>
                    <li>Students 18 or older hold their own FERPA rights and may make these requests directly.</li>
                </ul>
            </>
        )
    },
    {
        id: 'storage',
        tag: 'Security',
        title: 'Data Storage and Security',
        content: (
            <>
                <p>Account and session data is stored using Firebase Authentication and browser localStorage. We implement reasonable security measures including:</p>
                <ul>
                    <li>Encrypted authentication managed by Firebase (Google Cloud).</li>
                    <li>Role-based access controls so tutors, students, and admins can only access data appropriate to their role.</li>
                    <li>No plaintext passwords stored anywhere on the Platform.</li>
                </ul>
                <p>While we take reasonable precautions, no system is completely secure. Please use a strong password and report any suspicious activity immediately.</p>
            </>
        )
    },
    {
        id: 'cookies',
        tag: 'Browser Data',
        title: 'Cookies and Local Storage',
        content: (
            <>
                <p>We use browser localStorage (not cookies) to save your learning progress, quiz completions, and session preferences locally on your device. This data:</p>
                <ul>
                    <li>Never leaves your device unless explicitly synced to our servers.</li>
                    <li>Is cleared when you clear your browser's site data.</li>
                    <li>Is not shared with any third party.</li>
                </ul>
                <p>We do not use tracking cookies or third-party analytics scripts.</p>
            </>
        )
    },
    {
        id: 'rights',
        tag: 'Your Rights',
        title: 'Your Rights',
        content: (
            <>
                <p>You have the right to:</p>
                <ul>
                    <li><strong>Access:</strong> request a copy of the personal data we hold about you.</li>
                    <li><strong>Correction:</strong> update inaccurate information through your account settings or by contacting us.</li>
                    <li><strong>Deletion:</strong> request that your account and associated personal data be deleted.</li>
                    <li><strong>Portability:</strong> request your session history in a portable format.</li>
                </ul>
                <p>To exercise any of these rights, contact us through the <Link to="/contact">Contact page</Link>. We will respond within 5 school days.</p>
            </>
        )
    },
    {
        id: 'changes',
        tag: 'Updates',
        title: 'Changes to This Policy',
        content: (
            <>
                <p>We may update this Privacy Policy periodically. The "Last Updated" date at the top of this page will reflect any changes. We will notify users of significant changes via an in-app notice.</p>
                <p>Continued use of the Platform after changes are posted means you accept the revised policy.</p>
            </>
        )
    },
    {
        id: 'contact',
        tag: 'Help',
        title: 'Contact',
        content: (
            <>
                <p>For privacy-related questions, data requests, or concerns, please reach out through our <Link to="/contact">Contact page</Link>. You can also review our <Link to="/terms">Terms of Service</Link> for more information about how the Platform operates.</p>
            </>
        )
    },
];

function Privacy() {
    return (
        <div className="legal-page">
            <header className="legal-hero" aria-label="Privacy Policy header">
                <div className="legal-hero-inner">
                    <div className="legal-badge">Legal</div>
                    <h1>Privacy Policy</h1>
                    <p className="legal-hero-sub">
                        We believe privacy is a right, not a feature. Here is exactly what we collect, why, and how we protect it.
                    </p>
                    <div className="legal-updated">
                        <span className="legal-updated-dot" aria-hidden="true" />
                        Last updated: June 2026
                    </div>
                </div>
            </header>

            <main className="legal-content" id="privacy-content" aria-label="Privacy Policy content">
                <nav className="legal-toc" aria-label="Table of contents">
                    <span className="legal-toc-title">Contents</span>
                    {sections.map(s => (
                        <a key={s.id} href={`#${s.id}`}>{s.title}</a>
                    ))}
                </nav>

                {sections.map((s, i) => (
                    <section key={s.id} id={s.id} className="legal-section" aria-labelledby={`priv-h-${s.id}`}>
                        <div className="legal-section-header">
                            <div className="legal-section-num" aria-hidden="true">{String(i + 1).padStart(2, '0')}</div>
                            <div>
                                <span className="legal-section-tag">{s.tag}</span>
                                <h2 id={`priv-h-${s.id}`}>{s.title}</h2>
                            </div>
                        </div>
                        {s.content}
                    </section>
                ))}

                <div className="legal-cta" role="complementary" aria-label="Related pages">
                    <h3>Have questions about your data?</h3>
                    <p>We're transparent about everything. Reach out any time.</p>
                    <div className="legal-cta-links">
                        <Link to="/contact" className="legal-cta-btn primary">Contact Us</Link>
                        <Link to="/terms" className="legal-cta-btn ghost">Terms of Service</Link>
                        <Link to="/accessibility" className="legal-cta-btn ghost">Accessibility</Link>
                    </div>
                </div>
            </main>
        </div>
    );
}

export default Privacy;
